atendimento/urls.py
from atendimento.views import * 
from django.urls import path

app_name = 'atendimento'
urlpatterns = [
    path('triagem/', TriagemView.as_view(), name="triagem"),
    path('consulta/',ConsultaView.as_view(), name="consulta"),
    path('senha/', PedirSenhaView.as_view(), name="pedirSenha"),
    path('senhaconvencional/', SenhaConvencional.as_view(), name='senhaConvencional'),
    path('senhaprioritaria/', SenhaPrioritaria.as_view(), name="senhaPreferencial"),
    path('minhaSenha/', MinhaSenhaView.as_view(), name='minhaSenha')
]

sistemaHospitalar/urls.py
from django.contrib import admin
# from django.urls import path
# from django.conf.urls import url, include
from django.urls import path, include

###
from django.conf import settings
from django.conf.urls.static import static

###
from atendimento.views.index import IndexView
from atendimento.views.autenticacao.login import LoginView
from atendimento.views.autenticacao.logout import LogoutView

urlpatterns = [
    # LOGIN / LOGOUT 
    path('', IndexView.as_view(), name="index"),     
    path('p/login/', LoginView.as_view(), name='login'),    
    path('p/logout/', LogoutView.as_view(), name='logout'),  
     # ADMIN    
    path('admin/', admin.site.urls),
    ###
    path('atendimento/', include('atendimento.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atendimento/models/Consulta.py
from django.db import models
from atendimento.models import *

class Consulta(models.Model):
    paciente = models.ForeignKey(Triagem, editable=False, on_delete=models.PROTECT)
    medicoAtendente = models.ForeignKey(Pessoa, editable=False, on_delete=models.PROTECT)
    diagnostico = models.TextField('Diagnostico médico', blank=True, null=True)

atendimento/models/Triagem.py
from django.db import models
from atendimento.models import *
SEXO_CHOICES = (
    (1,'Masculino'),
    (2,'Feminino')
)

DOR_CHOICES = (
    (1,'Sim'),
    (2,'Não')
)

CLASSIFICACAO_CHOICES = (
    (1,'Emergência'),
    (2,'Muito Urgente'),
    (3,'Urgente'),
    (4,'Pouco Urgente'),
    (5,'Não Urgente')
)
ESTADO_CHOICES = (
    (1,'espera'),
    (2,'atendido')
)

class Triagem(models.Model):
    atendente = models.ForeignKey(Pessoa, editable=False, on_delete=models.PROTECT)
    nomePaciente = models.CharField(max_length=220)
    estado = models.IntegerField('Estado da Triagem',choices=ESTADO_CHOICES,null=False)
    senha = models.CharField(max_length=20, null=True, unique=True)
    sexo = models.IntegerField('Sexo', choices=SEXO_CHOICES, null=True) 
    queixaPrincipal = models.TextField('Queixa', blank=True, null=True)
    historicoBreve = models.TextField('Historico', blank=True, null=True) 
    observacaoObjetiva = models.TextField('Observações do Enfermeiro', blank=True, null=True)
    dor = models.IntegerField('Dor', choices=DOR_CHOICES, null=True) 
    frequenciaCardiaca = models.IntegerField() 
    frequenciaRespiratoria = models.IntegerField()
    pressaoArterial = models.IntegerField()
    temperatura = models.FloatField()
    classificacao = models.IntegerField('Classificacao', choices=CLASSIFICACAO_CHOICES, null=True)
    class Meta:
        verbose_name = "Triagem"
        verbose_name_plural = "Triagems"

    def __str__(self):
        return self.nomePaciente

    #def get_absolute_url(self):
    #    return reverse("Triagem_detail", kwargs={"pk": self.pk})

atendimento/models/pessoa.py
from django.db import models
from django.contrib.auth.models import User

TIPO_PESSOA_CHOICES = (
    (1, 'Medico'),
    (2, 'Enfermeira')
)

class Pessoa(models.Model):
    cpf = models.CharField('CPF', max_length=11, null=False, unique=True)
    nomeCompleto = models.CharField('Nome Completo', max_length=255)
    user = models.ForeignKey(User, null=False, editable=True, on_delete=models.PROTECT)
    tipo = models.IntegerField('Tipo pessoa', choices=TIPO_PESSOA_CHOICES, null=False)
    sala = models.CharField('Sala', max_length=120, null=False, unique=True)
    
    class Meta:
        verbose_name = "Pessoa"
        verbose_name_plural = "Pessoas"

    def __str__(self):
        return self.nomeCompleto

atendimento/models/senhas.py
from django.db import models

STATUS_CHOICES = (
    (1, 'Espera'),
    (2, 'Atendida')
)
TIPO_CHOICES = (
    (1, 'Convencional'),
    (2, 'Preferencial')
)
class Senha(models.Model):
    senha = models.CharField(max_length=20, unique=True)
    status = models.IntegerField('Status', choices=STATUS_CHOICES, null=False)
    tipo = models.IntegerField('Tipo', choices=TIPO_CHOICES, null=False)
    horaEmitida = models.DateTimeField(u'Data e Hora', auto_now_add=True)
    horaChamada = models.DateTimeField(u'Data e Hora', null=True)
    class Meta:
        verbose_name = "Senha"
        verbose_name_plural = "Senhas"

    def __str__(self):
        return self.senha

    # def get_absolute_url(self):
    #     return reverse("Senha_detail", kwargs={"pk": self.pk})

atendimento/forms/consultaForm.py
from dataclasses import field
from django.forms import *
from atendimento.models import *
class ConsultaForm(ModelForm):
    class Meta:
        model = Consulta
        fields = ["diagnostico"]
        widgets = {"diagnostico": Textarea(attrs={'class': 'medtextbox','placeholder':'Diagnostico','required': True})}
        

atendimento/forms/formLogin.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input','placeholder':'digite seu nome'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input','placeholder':'digite sua senha'}))

atendimento/forms/triagemForm.py
from dataclasses import field
from django.forms import *
from atendimento.models import *
class TriagemForm(ModelForm):
    class Meta:
        model = Triagem
        fields = "__all__"
        exclude = ["atendente","estado"]
        
        widgets = {
            "nomePaciente": TextInput(attrs={'class': 'enfinput','placeholder':'Nome do Paciente','required': True}),
            "queixaPrincipal": Textarea(attrs={'class': 'enfinput','placeholder':'Queixas Apresentadas Pelo Paciente','required': True}),
            "historicoBreve": Textarea(attrs={'class': 'enfinput','placeholder':'Historico Do Paciente','required': True}),
            "observacaoObjetiva": Textarea(attrs={'class': 'enfinput','placeholder':'Observações a Serem Concideradas.'}),
            "frequenciaCardiaca": NumberInput(attrs={'class': 'enfinput','required': True,'placeholder':'Qual a freqência cardíaca do paciênte?'}),
            "frequenciaRespiratoria": NumberInput(attrs={'class': 'enfinput','required': True,'placeholder':'Qual a freqência respiratória do paciênte?'}),
            "sexo": Select(attrs={'class': 'enfinput','required': True}),
            "dor": Select(attrs={'class': 'enfinput','required': True}),
            "pressaoArterial": NumberInput(attrs={'class': 'enfinput','required': True,'placeholder':'Qual a pressão arterial do paciênte?'}),
            "temperatura": NumberInput(attrs={'class': 'enfinput','required': True,'placeholder':'Qual a temperatura do paciênte?'}),
            "classificacao": Select(attrs={'class': 'enfinput','required': True}),
        }
            

atendimento/views/index.py
from django.shortcuts import render
from django.views import View


class IndexView(View):
    
    def get(self, request):
        template_name = 'index.html'
        context = {}
        return render(request, template_name, context)

atendimento/templates/autenticacao/login.html
{% extends 'base.html'%}
{% load static %}
{% block static_css %} 
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block title%} Login{% endblock %}
{% block conteudo %}
<div class = "line"> 
		
    >

</div>
<div class = "card"> 
    <div class = "icon">
    
        <div class = "draw">
        
        </div>
        
        <div class = "drawb">
        
        </div>
    
    </div>
    
    <form method="POST" action="{% url 'login' %}" class = "quest"> 
        {% csrf_token %}
        {% for field in form %}
            {{ field }}
        {% endfor %}

        {% if error %}
            <span style="color: red;">{{ error }}</span>
            <br><br>
        {% endif %}
        
        <input class = "butto" type = "submit" value = "login">
    
    </form>

</div>
{% endblock%}

atendimento/templates/base/consulta.html
{% extends 'base.html'%}
{% load static %}
{% block static_css %}
<link rel="stylesheet" href="{% static 'css/consulta.css' %}">
{% endblock %}
{% block conteudo %}
<div class = "medquest"> 
    <div>
        <button class = "medbutto" onclick="location.href=`{% url 'atendimento:consulta'%}`">Chamar Próximo</button>
    </div>
</div>

<form method="POST" action="." class = "cmd"> 
    <a class = "biggertext">>Descrição da triagem</a><br><br>
	<!--deixei em branco a parte em frente aos nome pois depende da recuperação dos dados do bd-->
	<a class = "medlinetext">Nome Do Paciente: {{nomePaciente}}</a><br><br>
	<a class = "medlinetext">Queixas Do Paciente: {{queixa}}</a><br><br>
	<a class = "medlinetext">Historico Breve: {{historico}}</a><br><br>
	<a class = "medlinetext">Observações do Enfermeiro(a): {{obs}}</a><br><br>
    <a class = "medlinetext">Dor: {{dor}}</a><br><br>
    <a class = "medlinetext">Frequência Cardiaca: {{fc}}</a><br><br>
    <a class = "medlinetext">Frequência Respiratoria: {{fr}}</a><br><br>
    <a class = "medlinetext">Pressao Arterial: {{pa}}</a><br><br>
    <a class = "medlinetext">temperatura: {{temp}}</a><br><br>
    {% csrf_token %}
    {% for field in form %}
        <label for="{{ field.name }}" class = "medlinetext">{{ field.label }}: </label>
        {{ field }}
    {% endfor %}
    {% if form%}
    <div class="priority" >
        <input class = "butto" type = "submit" value = "Enviar" style="font-weight:bold">
    </div>
    {% endif %}
    {% if error %}
        <span style="color: red;">{{ error }}</span>
        <br><br>
    {% endif %}
</form>
{% endblock%}

atendimento/templates/base/triagem.html
{% extends 'base.html'%}
{% load static %}
{% block static_css %}
<link rel="stylesheet" href="{% static 'css/triagem.css' %}">
{% endblock %}
{% block conteudo %}
<div class = "medquest"> 
    <div>
        <button class = "medbutto" onclick="location.href=`{% url 'atendimento:triagem'%}`">Chamar Próximo</button>
    </div>
</div>

<form method="POST" action="." class = "cmd"> 
    {% csrf_token %}
    {% for field in form %}
        <label for="{{ field.name }}" class = "enflinetext">{{ field.label }}: </label>
        {{ field }}
    {% endfor %}
    {% if form%}
    <div class="priority" >
        <input class = "enfbutto" type = "submit" value = "Enviar" style="font-weight:bold">
    </div>
    {% endif %}
    {% if error %}
        <span style="color: red;">{{ error }}</span>
        <br><br>
    {% endif %}
</form>
{% endblock%}

atendimento/templates/index.html
{% extends 'base.html'%}
{% load static %}
{% block static_css %} 
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block conteudo %}
<div> 
		
    <div class = "nav"> 
    
        <button class = "butto" > monitor </button>
        <button class = "butto" onclick="location.href=`{% url 'atendimento:pedirSenha'%}`"> paciente </button>
        <button class = "butto" onclick="location.href=`{% url 'login'%}`"> login </button>
    
    </div>
    
    <div class = "texttypper"> 
    
        Bug hospital, achando o que tem de errado no seu corpo;
    
    </div>
    
    <div class = "line"> > </div>

</div>
{% endblock%}

atendimento/templates/senhas/pedirSenha.html
{% extends 'base.html'%}
{% load static %}
{% block static_css %} 
<link rel="stylesheet" href="{% static 'css/pedirSenha.css' %}">
{% endblock %}
{% block conteudo %}
<div class = "cmd"> 
		
    <a class = "biggertext"> > Emissâo de senhas :  </a>
    
    <div class = "priority">
    
        <button class = "butto" onclick="location.href=`{% url 'atendimento:senhaPreferencial'%}`"> Prioritária </button>
        <button class = "butto" onclick="location.href=`{% url 'atendimento:senhaConvencional'%}`">  Normal </button>
    
    </div>
    
    <a class = "line"> > </a>

</div>

<div class = "centerdiv"> 
    
        <a class = "biggertext"> Já já você  <br> entra na </a> <a class = "bugline"> fila </a>
    
</div>
{% endblock%}

atendimento/templates/senhas/senhas.html
{% extends 'base.html'%}
{% load static %}
{% block static_css %} 
<link rel="stylesheet" href="{% static 'css/senha.css' %}">
{% endblock %}
{% block static_js %}
{% endblock %} 
{% block conteudo %}
<div class = "texttypper" load="func()"> 
		
    Sua senha é : <a class = "bugline"> {{request.session.senha}}</a>

</div>
{% endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

	<head>
	
		<meta charset="utf-8">
		<title>{%block title%}Bug Hospital{% endblock %}</title>
		<link href="{% static  'libs/bootstrap-5.0.1/css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/base.css' %}" rel = "stylesheet">
        {% block static_css %} {% endblock %}
		{% block static_js %} 
		{% endblock %} 
	</head>
	
	<body>
		{%block conteudo%}
		{% endblock %}		
	</body>
     
</html>